"""Generate reusable illustrated UI bindings from recorded owner uploads."""
import argparse
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
BINDINGS = ROOT / 'resources/ui/v2/icons/upload-bindings.json'
OUTPUT = ROOT / 'src/shared/UIIconAssets.luau'


def compile_bindings():
    data = json.loads(BINDINGS.read_text())
    result = {}
    for entry in data['assets']:
        key, asset_id = entry['key'], entry.get('robloxAssetId')
        if key in result or not re.fullmatch(r'[a-z_]+', key):
            raise ValueError('Invalid or duplicate icon key')
        if asset_id is not None and not re.fullmatch(r'[1-9][0-9]*', str(asset_id)):
            raise ValueError('Invalid Roblox image ID')
        result[key] = f'rbxassetid://{asset_id}' if asset_id is not None else ''
    if set(result) != {'trophy', 'dinos', 'egg', 'home', 'fusion', 'shield', 'amber'}:
        raise ValueError('Expected the seven original illustrated icons')
    return '--!strict\n-- Generated by tools/bind_ui_icons.py. Empty IDs use native graphics.\nreturn {\n' + ''.join(
        f'    {key} = {json.dumps(uri)},\n' for key, uri in result.items()
    ) + '}\n'


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    content = compile_bindings()
    if args.check:
        if OUTPUT.read_text() != content:
            raise SystemExit('UI icon mapping is stale. Run python tools/bind_ui_icons.py')
    else:
        OUTPUT.write_text(content)
    print('UI icon bindings verified' if args.check else 'UI icon bindings generated')
