"""Compile recorded Roblox image IDs into the shared runtime mapping; no upload or fabricated IDs."""
import argparse,json,re
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
BINDINGS=ROOT/'resources/ui/v2/layers/upload-bindings.json'
OUTPUT=ROOT/'src/shared/ArtworkAssets.luau'
def compile_bindings(path=BINDINGS):
    data=json.loads(Path(path).read_text())
    entries=data.get('assets', data.get('bindings'))
    if entries is None: raise ValueError('Missing assets')
    result={}
    for entry in entries:
        key=entry.get('logicalId',entry.get('key'))
        if not isinstance(key,str) or not re.fullmatch(r'[a-z_]+',key) or key in result:raise ValueError('Invalid or duplicate asset key')
        asset_id=entry.get('robloxAssetId')
        uri=entry.get('imageContentUri')
        if asset_id is not None and (isinstance(asset_id,bool) or not re.fullmatch(r'[1-9][0-9]*',str(asset_id))):raise ValueError('Invalid Roblox image ID')
        if uri is not None and not re.fullmatch(r'rbxassetid://[1-9][0-9]*',uri):raise ValueError('Invalid image content URI')
        result[key]=uri or (f'rbxassetid://{asset_id}' if asset_id is not None else '')
    expected={'fossil_centerpiece','aura_meadow_ring','aura_tidal_ring','aura_royal_ring','potion_speed_base','potion_growth_base','mutation_gold','mutation_diamond','catches_mark'}
    if set(result)!=expected:raise ValueError('Artwork mapping must contain the nine preferred asset keys')
    return '--!strict\n-- Generated by tools/bind_artwork.py from upload-bindings.json. Empty IDs use native icons.\nreturn {\n'+''.join(f'    {key} = {json.dumps(uri)},\n' for key,uri in result.items())+'}\n'
if __name__=='__main__':
    parser=argparse.ArgumentParser();parser.add_argument('--bindings',type=Path,default=BINDINGS);parser.add_argument('--output',type=Path,default=OUTPUT);parser.add_argument('--check',action='store_true');args=parser.parse_args()
    content=compile_bindings(args.bindings)
    if args.check:
        if args.output.read_text()!=content:raise SystemExit('Runtime artwork mapping is stale. Run python tools/bind_artwork.py')
    else:args.output.write_text(content)
    print('Artwork binding mapping verified' if args.check else 'Artwork binding mapping generated')
