"""Generate reusable model bindings and authored world materials from verified IDs."""
import argparse
import json
from pathlib import Path
import xml.etree.ElementTree as ET

ROOT = Path(__file__).resolve().parents[1]
BASES = {"Grass": 1280, "Rock": 896, "Wood": 512}


def outputs():
    manifest = json.loads((ROOT / "resources/visual-upgrade-bindings.json").read_text())
    models = {item["id"]: item["assetId"] for item in manifest["models"]}
    materials = manifest["worldMaterials"]
    for asset in [*models.values(), *(m[k] for m in materials for k in ("color", "normal", "roughness", "metal"))]:
        if asset != "" and (not isinstance(asset, str) or not asset.isdecimal() or int(asset) <= 0):
            raise ValueError("Expected an actual positive asset ID or empty fallback binding")
    model_luau = '--!strict\n-- Generated by tools/bind_visual_assets.py; empty IDs retain native geometry.\nreturn {\n'
    model_luau += ''.join(f'    {key} = "{value}",\n' for key, value in models.items()) + '}\n'
    root = ET.Element("roblox", {"version": "4"})
    service = ET.SubElement(root, "Item", {"class": "MaterialService", "referent": "MATERIALS"})
    props = ET.SubElement(service, "Properties")
    ET.SubElement(props, "string", {"name": "Name"}).text = "MaterialService"
    for m in materials:
        ET.SubElement(props, "string", {"name": m["base"] + "Name"}).text = m["name"] if m["color"] else m["base"]
        if not m["color"]:
            continue
        node = ET.SubElement(service, "Item", {"class": "MaterialVariant", "referent": m["name"]})
        p = ET.SubElement(node, "Properties")
        ET.SubElement(p, "string", {"name": "Name"}).text = m["name"]
        ET.SubElement(p, "token", {"name": "BaseMaterial"}).text = str(BASES[m["base"]])
        ET.SubElement(p, "token", {"name": "MaterialPattern"}).text = "1"
        ET.SubElement(p, "float", {"name": "StudsPerTile"}).text = str(m["tile"])
        for field, key in (("ColorMap", "color"), ("NormalMap", "normal"), ("RoughnessMap", "roughness"), ("MetalnessMap", "metal")):
            content = ET.SubElement(p, "Content", {"name": field})
            ET.SubElement(content, "url").text = "rbxassetid://" + m[key] if m[key] else ""
    ET.indent(root, space="  ")
    return {ROOT / "src/shared/ResourceMeshAssets.luau": model_luau,
            ROOT / "resources/world-materials.rbxmx": ET.tostring(root, encoding="unicode") + "\n"}


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    for path, content in outputs().items():
        if args.check:
            if path.read_text(encoding="utf-8") != content:
                raise SystemExit(f"Stale visual binding: {path}")
        else:
            path.write_text(content, encoding="utf-8")
    print("Visual asset bindings checked" if args.check else "Visual asset bindings generated")
